services:
  app:
    container_name: chrono-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${WEB_PORT:-3000}:3000"

    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0

    networks:
      - app

networks:
  app:
    driver: bridge